name: Publish Provider

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch: {}

env:
  GO_VERSION: '1.23'

jobs:
  publish-provider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Provider Binary
        run: |
          go mod tidy
          go build -o terraform-provider-zitadel .

      - name: Upload Provider Binary as GitHub Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: terraform-provider-zitadel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}